local g = vim.g
local o = vim.o

g.mapleader = ','

g.ale_sign_error = 'X'
g.ale_sign_warning = '!'
g.ale_sign_info = 'i'
g.ale_sign_style_error = 'S'
g.ale_sign_style_warning = 'S'
g.ale_sign_highlight_linenrs = 1

g.fzf_preview_window = 'right:50%'
g.gitgutter_map_keys = 0
g.gitgutter_sign_allow_clobber = 1
g.pandoc_preview_pdf_cmd = "zathura"
g.startify_session_persistence = 1
g.tex_conceal = ""
g.user_emmet_install_global = 0
g.user_emmet_leader_key = ','

o.autowriteall = true
o.autoread = true
o.background = "dark"
o.breakindent = true -- Indents word-wrapped lines as much as the line above
o.clipboard = "unnamedplus"
o.cmdheight = 2
o.complete = "kspell" -- spell check
o.completeopt = "preview"
o.conceallevel = 1
o.diffopt = "hiddenoff"
o.equalalways = true
o.fillchars = "vert:|,fold:~,stl:-,stlnc:-"
o.expandtab = true
o.formatoptions = "lt" -- Ensures word-wrap does not split words
o.hidden = true
o.ignorecase = true
o.lazyredraw = true
o.lbr = true
o.list = true
o.listchars = "tab:> ,trail:·"
o.mouse = "a"
o.backup = false
o.writebackup = false
o.cursorline = true
o.showmode = false -- hides -- INSERT --
o.swapfile = false
o.eb = false -- no error bells
o.wb = false
o.vb = false
o.number = true
o.rnu = true
o.shiftwidth = 4
o.shortmess = "caFTW"
o.si = true  -- Smart indent
o.signcolumn = "yes:1"
o.smartcase = true
o.softtabstop = 4
o.scrolloff = 5
o.splitbelow = true
o.splitright = true
o.tabstop = 4 -- Tab size is 4
o.textwidth = 80
o.tags = "./tags;"
o.termguicolors = false
o.undodir = os.getenv("HOME") .. "/.local/share/nvim/undodir"
o.undofile = true
o.undolevels = 1000
o.undoreload = 10000
o.updatetime = 300
o.whichwrap = "<,>,h,l"
o.wildignore = "*/node_modules,*/node_modules/*,.git,.git/*,tags,*/dist,*/dist/*"
o.wrap = true
